# config.yaml

# 맵 크기 (단위: m, 각 셀은 1m×1m)
width: 5
height: 5

# 맵 데이터: 문자열 리스트
# '0': normal, '1': wall, '2': trap, '3': goal
map:
  - "00000"
  - "01001"
  - "00000"
  - "00010"
  - "01003"

# (선택) 에이전트 시작 셀 (row, col). 주석 처리 시 자동 선택.
start: [0, 0]